#!/bin/sh


ssh -X X88@quanta-rabi.mit.edu << ENDSSH

export DISPLAY=:0
xrandr --output DP-1 --brightness $1
xrandr --output DP-0 --brightness $1


#sudo su - www-data -c "env PATH=$PATH wp --path='/data/www/blog/' media import $dir/screenshot_$filename-0.png"
ENDSSH

exit 0